
package ir.carpino.settlement.entity.gateway.pasargad.userservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserServices", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", wsdlLocation = "https://ib.bpi.ir/WebServices/UserServices.asmx?wsdl")
public class UserServices
    extends Service
{

    private final static URL USERSERVICES_WSDL_LOCATION;
    private final static WebServiceException USERSERVICES_EXCEPTION;
    private final static QName USERSERVICES_QNAME = new QName("http://ibank.toranj.fanap.co.ir/UserServices", "UserServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ib.bpi.ir/WebServices/UserServices.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICES_WSDL_LOCATION = url;
        USERSERVICES_EXCEPTION = e;
    }

    public UserServices() {
        super(__getWsdlLocation(), USERSERVICES_QNAME);
    }

    public UserServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICES_QNAME, features);
    }

    public UserServices(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICES_QNAME);
    }

    public UserServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICES_QNAME, features);
    }

    public UserServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServicesSoap
     */
    @WebEndpoint(name = "UserServicesSoap")
    public UserServicesSoap getUserServicesSoap() {
        return super.getPort(new QName("http://ibank.toranj.fanap.co.ir/UserServices", "UserServicesSoap"), UserServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServicesSoap
     */
    @WebEndpoint(name = "UserServicesSoap")
    public UserServicesSoap getUserServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibank.toranj.fanap.co.ir/UserServices", "UserServicesSoap"), UserServicesSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns UserServicesSoap
     */
    @WebEndpoint(name = "UserServicesSoap12")
    public UserServicesSoap getUserServicesSoap12() {
        return super.getPort(new QName("http://ibank.toranj.fanap.co.ir/UserServices", "UserServicesSoap12"), UserServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServicesSoap
     */
    @WebEndpoint(name = "UserServicesSoap12")
    public UserServicesSoap getUserServicesSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibank.toranj.fanap.co.ir/UserServices", "UserServicesSoap12"), UserServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICES_EXCEPTION!= null) {
            throw USERSERVICES_EXCEPTION;
        }
        return USERSERVICES_WSDL_LOCATION;
    }

}
