
package ir.carpino.settlement.entity.gateway.pasargad.userservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ir.carpino.settlement.entity.gateway.pasargad.signatureservice.ActionResult;
import ir.carpino.settlement.entity.gateway.pasargad.signatureservice.BaseInput;
import ir.carpino.settlement.entity.gateway.pasargad.signatureservice.DepositAmountInput;
import ir.carpino.settlement.entity.gateway.pasargad.signatureservice.InvoiceInput;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServicesSoap", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
@XmlSeeAlso({
    ObjectFactory.class,
    ObjectFactory.class
})
public interface UserServicesSoap {


    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDataToSign", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetDataToSign")
    @WebResult(name = "GetDataToSignResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetDataToSign", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDataToSign")
    @ResponseWrapper(localName = "GetDataToSignResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDataToSignResponse")
    public String getDataToSign(
            @WebParam(name = "input", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    BaseInput input);

    /**
     * 
     * @param input
     * @return
     *     returns ir.fanap.ibank.signatureservice.ActionResult
     */
    @WebMethod(operationName = "GetInvoice", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetInvoice")
    @WebResult(name = "GetInvoiceResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetInvoice", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetInvoice")
    @ResponseWrapper(localName = "GetInvoiceResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetInvoiceResponse")
    public ActionResult getInvoice(
            @WebParam(name = "input", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    InvoiceInput input);

    /**
     * 
     * @param input
     * @return
     *     returns ir.fanap.ibank.signatureservice.ActionResult
     */
    @WebMethod(operationName = "GetDepositAmount", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetDepositAmount")
    @WebResult(name = "GetDepositAmountResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetDepositAmount", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositAmount")
    @ResponseWrapper(localName = "GetDepositAmountResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositAmountResponse")
    public ActionResult getDepositAmount(
            @WebParam(name = "input", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    DepositAmountInput input);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferMoney", action = "http://ibank.toranj.fanap.co.ir/UserServices/TransferMoney")
    @WebResult(name = "TransferMoneyResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "TransferMoney", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.TransferMoney")
    @ResponseWrapper(localName = "TransferMoneyResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.TransferMoneyResponse")
    public String transferMoney(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferMoneySetOrder", action = "http://ibank.toranj.fanap.co.ir/UserServices/TransferMoneySetOrder")
    @WebResult(name = "TransferMoneySetOrderResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "TransferMoneySetOrder", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.TransferMoneySetOrder")
    @ResponseWrapper(localName = "TransferMoneySetOrderResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.TransferMoneySetOrderResponse")
    public String transferMoneySetOrder(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDepositBalance", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetDepositBalance")
    @WebResult(name = "GetDepositBalanceResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetDepositBalance", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositBalance")
    @ResponseWrapper(localName = "GetDepositBalanceResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositBalanceResponse")
    public String getDepositBalance(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDepositBaseInfo", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetDepositBaseInfo")
    @WebResult(name = "GetDepositBaseInfoResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetDepositBaseInfo", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositBaseInfo")
    @ResponseWrapper(localName = "GetDepositBaseInfoResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositBaseInfoResponse")
    public String getDepositBaseInfo(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDepositInvoice", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetDepositInvoice")
    @WebResult(name = "GetDepositInvoiceResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetDepositInvoice", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositInvoice")
    @ResponseWrapper(localName = "GetDepositInvoiceResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositInvoiceResponse")
    public String getDepositInvoice(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTransferMoneyState", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetTransferMoneyState")
    @WebResult(name = "GetTransferMoneyStateResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetTransferMoneyState", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetTransferMoneyState")
    @ResponseWrapper(localName = "GetTransferMoneyStateResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetTransferMoneyStateResponse")
    public String getTransferMoneyState(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConvertDepositNumberToSheba", action = "http://ibank.toranj.fanap.co.ir/UserServices/ConvertDepositNumberToSheba")
    @WebResult(name = "ConvertDepositNumberToShebaResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "ConvertDepositNumberToSheba", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ConvertDepositNumberToSheba")
    @ResponseWrapper(localName = "ConvertDepositNumberToShebaResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ConvertDepositNumberToShebaResponse")
    public String convertDepositNumberToSheba(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConfirmCustomerInfo", action = "http://ibank.toranj.fanap.co.ir/UserServices/ConfirmCustomerInfo")
    @WebResult(name = "ConfirmCustomerInfoResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "ConfirmCustomerInfo", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ConfirmCustomerInfo")
    @ResponseWrapper(localName = "ConfirmCustomerInfoResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ConfirmCustomerInfoResponse")
    public String confirmCustomerInfo(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CardToCardTransfer", action = "http://ibank.toranj.fanap.co.ir/UserServices/CardToCardTransfer")
    @WebResult(name = "CardToCardTransferResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "CardToCardTransfer", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CardToCardTransfer")
    @ResponseWrapper(localName = "CardToCardTransferResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CardToCardTransferResponse")
    public String cardToCardTransfer(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CardToCardTransferWithoutSubDeposit", action = "http://ibank.toranj.fanap.co.ir/UserServices/CardToCardTransferWithoutSubDeposit")
    @WebResult(name = "CardToCardTransferWithoutSubDepositResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "CardToCardTransferWithoutSubDeposit", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CardToCardTransferWithoutSubDeposit")
    @ResponseWrapper(localName = "CardToCardTransferWithoutSubDepositResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CardToCardTransferWithoutSubDepositResponse")
    public String cardToCardTransferWithoutSubDeposit(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCardInformation", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetCardInformation")
    @WebResult(name = "GetCardInformationResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetCardInformation", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardInformation")
    @ResponseWrapper(localName = "GetCardInformationResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardInformationResponse")
    public String getCardInformation(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCardInformationByCardInfo", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetCardInformationByCardInfo")
    @WebResult(name = "GetCardInformationByCardInfoResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetCardInformationByCardInfo", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardInformationByCardInfo")
    @ResponseWrapper(localName = "GetCardInformationByCardInfoResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardInformationByCardInfoResponse")
    public String getCardInformationByCardInfo(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConvertShebaToDepositNumber", action = "http://ibank.toranj.fanap.co.ir/UserServices/ConvertShebaToDepositNumber")
    @WebResult(name = "ConvertShebaToDepositNumberResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "ConvertShebaToDepositNumber", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ConvertShebaToDepositNumber")
    @ResponseWrapper(localName = "ConvertShebaToDepositNumberResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ConvertShebaToDepositNumberResponse")
    public String convertShebaToDepositNumber(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCustomerInfoByDepositNumberAndDate", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetCustomerInfoByDepositNumberAndDate")
    @WebResult(name = "GetCustomerInfoByDepositNumberAndDateResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetCustomerInfoByDepositNumberAndDate", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCustomerInfoByDepositNumberAndDate")
    @ResponseWrapper(localName = "GetCustomerInfoByDepositNumberAndDateResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCustomerInfoByDepositNumberAndDateResponse")
    public String getCustomerInfoByDepositNumberAndDate(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetShebaByCardNumber", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetShebaByCardNumber")
    @WebResult(name = "GetShebaByCardNumberResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetShebaByCardNumber", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetShebaByCardNumber")
    @ResponseWrapper(localName = "GetShebaByCardNumberResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetShebaByCardNumberResponse")
    public String getShebaByCardNumber(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDepositNumberByCardNumber", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetDepositNumberByCardNumber")
    @WebResult(name = "GetDepositNumberByCardNumberResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetDepositNumberByCardNumber", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositNumberByCardNumber")
    @ResponseWrapper(localName = "GetDepositNumberByCardNumberResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositNumberByCardNumberResponse")
    public String getDepositNumberByCardNumber(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCardTransactionsList", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetCardTransactionsList")
    @WebResult(name = "GetCardTransactionsListResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetCardTransactionsList", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardTransactionsList")
    @ResponseWrapper(localName = "GetCardTransactionsListResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardTransactionsListResponse")
    public String getCardTransactionsList(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetShebaInfo", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetShebaInfo")
    @WebResult(name = "GetShebaInfoResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetShebaInfo", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetShebaInfo")
    @ResponseWrapper(localName = "GetShebaInfoResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetShebaInfoResponse")
    public String getShebaInfo(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BillPaymentByDeposit", action = "http://ibank.toranj.fanap.co.ir/UserServices/BillPaymentByDeposit")
    @WebResult(name = "BillPaymentByDepositResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "BillPaymentByDeposit", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.BillPaymentByDeposit")
    @ResponseWrapper(localName = "BillPaymentByDepositResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.BillPaymentByDepositResponse")
    public String billPaymentByDeposit(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BillPaymentByCard", action = "http://ibank.toranj.fanap.co.ir/UserServices/BillPaymentByCard")
    @WebResult(name = "BillPaymentByCardResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "BillPaymentByCard", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.BillPaymentByCard")
    @ResponseWrapper(localName = "BillPaymentByCardResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.BillPaymentByCardResponse")
    public String billPaymentByCard(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PurchaseCharge", action = "http://ibank.toranj.fanap.co.ir/UserServices/PurchaseCharge")
    @WebResult(name = "PurchaseChargeResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "PurchaseCharge", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.PurchaseCharge")
    @ResponseWrapper(localName = "PurchaseChargeResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.PurchaseChargeResponse")
    public String purchaseCharge(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CoreBatchTransferPaya", action = "http://ibank.toranj.fanap.co.ir/UserServices/CoreBatchTransferPaya")
    @WebResult(name = "CoreBatchTransferPayaResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "CoreBatchTransferPaya", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CoreBatchTransferPaya")
    @ResponseWrapper(localName = "CoreBatchTransferPayaResponseStr", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CoreBatchTransferPayaResponseStr")
    public String coreBatchTransferPaya(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPayaList", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetPayaList")
    @WebResult(name = "GetPayaListResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetPayaList", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetPayaList")
    @ResponseWrapper(localName = "GetPayaListResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetPayaListResponse")
    public String getPayaList(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IssueOtherChequesDeposit", action = "http://ibank.toranj.fanap.co.ir/UserServices/IssueOtherChequesDeposit")
    @WebResult(name = "IssueOtherChequesDepositResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "IssueOtherChequesDeposit", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.IssueOtherChequesDeposit")
    @ResponseWrapper(localName = "IssueOtherChequesDepositResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.IssueOtherChequesDepositResponse")
    public String issueOtherChequesDeposit(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchTransferMoney", action = "http://ibank.toranj.fanap.co.ir/UserServices/BatchTransferMoney")
    @WebResult(name = "BatchTransferMoneyResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "BatchTransferMoney", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.BatchTransferMoney")
    @ResponseWrapper(localName = "BatchTransferMoneyResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.BatchTransferMoneyResponse")
    public String batchTransferMoney(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCardToCardTransferReport", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetCardToCardTransferReport")
    @WebResult(name = "GetCardToCardTransferReportResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetCardToCardTransferReport", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardToCardTransferReport")
    @ResponseWrapper(localName = "GetCardToCardTransferReportResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardToCardTransferReportResponse")
    public String getCardToCardTransferReport(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckCustomerExistenceByContactNumberAndIdNumber", action = "http://ibank.toranj.fanap.co.ir/UserServices/CheckCustomerExistenceByContactNumberAndIdNumber")
    @WebResult(name = "CheckCustomerExistenceByContactNumberAndIdNumberResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "CheckCustomerExistenceByContactNumberAndIdNumber", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CheckCustomerExistenceByContactNumberAndIdNumber")
    @ResponseWrapper(localName = "CheckCustomerExistenceByContactNumberAndIdNumberResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CheckCustomerExistenceByContactNumberAndIdNumberResponse")
    public String checkCustomerExistenceByContactNumberAndIdNumber(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBonCardOrganizationAccounts", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetBonCardOrganizationAccounts")
    @WebResult(name = "GetBonCardOrganizationAccountsResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetBonCardOrganizationAccounts", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetBonCardOrganizationAccounts")
    @ResponseWrapper(localName = "GetBonCardOrganizationAccountsResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetBonCardOrganizationAccountsResponse")
    public String getBonCardOrganizationAccounts(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChargeOrganizationBonCards", action = "http://ibank.toranj.fanap.co.ir/UserServices/ChargeOrganizationBonCards")
    @WebResult(name = "ChargeOrganizationBonCardsResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "ChargeOrganizationBonCards", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ChargeOrganizationBonCards")
    @ResponseWrapper(localName = "ChargeOrganizationBonCardsResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ChargeOrganizationBonCardsResponse")
    public String chargeOrganizationBonCards(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrganizationBonCards", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetOrganizationBonCards")
    @WebResult(name = "GetOrganizationBonCardsResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetOrganizationBonCards", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBonCards")
    @ResponseWrapper(localName = "GetOrganizationBonCardsResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBonCardsResponse")
    public String getOrganizationBonCards(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayInstallment", action = "http://ibank.toranj.fanap.co.ir/UserServices/PayInstallment")
    @WebResult(name = "PayInstallmentResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "PayInstallment", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.PayInstallment")
    @ResponseWrapper(localName = "PayInstallmentResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.PayInstallmentResponse")
    public String payInstallment(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTransactionInquiries", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetTransactionInquiries")
    @WebResult(name = "GetTransactionInquiriesResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetTransactionInquiries", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetTransactionInquiries")
    @ResponseWrapper(localName = "GetTransactionInquiriesResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetTransactionInquiriesResponse")
    public String getTransactionInquiries(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetsubmissionCheque", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetsubmissionCheque")
    @WebResult(name = "GetsubmissionChequeResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetsubmissionCheque", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetsubmissionCheque")
    @ResponseWrapper(localName = "GetsubmissionChequeResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetsubmissionChequeResponse")
    public String getsubmissionCheque(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTransactionsOfOrganizationBonCards", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetTransactionsOfOrganizationBonCards")
    @WebResult(name = "GetTransactionsOfOrganizationBonCardsResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetTransactionsOfOrganizationBonCards", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetTransactionsOfOrganizationBonCards")
    @ResponseWrapper(localName = "GetTransactionsOfOrganizationBonCardsResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetTransactionsOfOrganizationBonCardsResponse")
    public String getTransactionsOfOrganizationBonCards(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBonCardTransactionsList", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetBonCardTransactionsList")
    @WebResult(name = "GetBonCardTransactionsListResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetBonCardTransactionsList", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetBonCardTransactionsList")
    @ResponseWrapper(localName = "GetBonCardTransactionsListResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetBonCardTransactionsListResponse")
    public String getBonCardTransactionsList(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReverseWholeChargeOfOrganizationBonCards", action = "http://ibank.toranj.fanap.co.ir/UserServices/ReverseWholeChargeOfOrganizationBonCards")
    @WebResult(name = "ReverseWholeChargeOfOrganizationBonCardsResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "ReverseWholeChargeOfOrganizationBonCards", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ReverseWholeChargeOfOrganizationBonCards")
    @ResponseWrapper(localName = "ReverseWholeChargeOfOrganizationBonCardsResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.ReverseWholeChargeOfOrganizationBonCardsResponse")
    public String reverseWholeChargeOfOrganizationBonCards(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrganizationBonCardState", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetOrganizationBonCardState")
    @WebResult(name = "GetOrganizationBonCardStateResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetOrganizationBonCardState", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBonCardState")
    @ResponseWrapper(localName = "GetOrganizationBonCardStateResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBonCardStateResponse")
    public String getOrganizationBonCardState(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrganizationBatchChargeDescriptions", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetOrganizationBatchChargeDescriptions")
    @WebResult(name = "GetOrganizationBatchChargeDescriptionsResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetOrganizationBatchChargeDescriptions", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBatchChargeDescriptions")
    @ResponseWrapper(localName = "GetOrganizationBatchChargeDescriptionsResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBatchChargeDescriptionsResponse")
    public String getOrganizationBatchChargeDescriptions(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrganizationBatchChargeReport", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetOrganizationBatchChargeReport")
    @WebResult(name = "GetOrganizationBatchChargeReportResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetOrganizationBatchChargeReport", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBatchChargeReport")
    @ResponseWrapper(localName = "GetOrganizationBatchChargeReportResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetOrganizationBatchChargeReportResponse")
    public String getOrganizationBatchChargeReport(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InquiryBillPayment", action = "http://ibank.toranj.fanap.co.ir/UserServices/InquiryBillPayment")
    @WebResult(name = "InquiryBillPaymentResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "InquiryBillPayment", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.InquiryBillPayment")
    @ResponseWrapper(localName = "InquiryBillPaymentResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.InquiryBillPaymentResponse")
    public String inquiryBillPayment(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateWebServiceUser", action = "http://ibank.toranj.fanap.co.ir/UserServices/CreateWebServiceUser")
    @WebResult(name = "CreateWebServiceUserResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "CreateWebServiceUser", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CreateWebServiceUser")
    @ResponseWrapper(localName = "CreateWebServiceUserResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.CreateWebServiceUserResponse")
    public String createWebServiceUser(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCardBalance", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetCardBalance")
    @WebResult(name = "GetCardBalanceResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetCardBalance", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardBalance")
    @ResponseWrapper(localName = "GetCardBalanceResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetCardBalanceResponse")
    public String getCardBalance(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBillNumberGeneratorDoc", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetBillNumberGeneratorDoc")
    @WebResult(name = "GetBillNumberGeneratorDocResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetBillNumberGeneratorDoc", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetBillNumberGeneratorDoc")
    @ResponseWrapper(localName = "GetBillNumberGeneratorDocResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetBillNumberGeneratorDocResponse")
    public String getBillNumberGeneratorDoc(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

    /**
     * 
     * @param request
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDepositBillStructure", action = "http://ibank.toranj.fanap.co.ir/UserServices/GetDepositBillStructure")
    @WebResult(name = "GetDepositBillStructureResult", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
    @RequestWrapper(localName = "GetDepositBillStructure", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositBillStructure")
    @ResponseWrapper(localName = "GetDepositBillStructureResponse", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices", className = "ir.co.fanap.toranj.ibank.userservices.GetDepositBillStructureResponse")
    public String getDepositBillStructure(
            @WebParam(name = "request", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String request,
            @WebParam(name = "signature", targetNamespace = "http://ibank.toranj.fanap.co.ir/UserServices")
                    String signature);

}
